### ISSUE TITLE
os.platform returns browser in Electron

### ISSUE THREAD

**Issue by igsnow** [dopecodez/pingman#10]
The error is as follows

platformNotSupportedError: Platform browser is not supported
    at Object.createBuilder [as default] (http://localhost:3000/static/js/0.chunk.js:1382:11)
    at ping (http://localhost:3000/static/js/0.chunk.js:1911:43)
    at getPrintStatus (http://localhost:3000/static/js/main.chunk.js:165:30)
    at http://localhost:3000/static/js/main.chunk.js:140:5
    at commitHookEffectListMount (http://localhost:3000/static/js/0.chunk.js:24894:30)
    at commitPassiveHookEffects (http://localhost:3000/static/js/0.chunk.js:24931:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:5476:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:5525:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:5578:35)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/0.chunk.js:27995:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:35079:16)
    at runWithPriority$1 (http://localhost:3000/static/js/0.chunk.js:16363:14)
    at flushPassiveEffects (http://localhost:3000/static/js/0.chunk.js:27963:16)
    at http://localhost:3000/static/js/0.chunk.js:27842:15
    at workLoop (http://localhost:3000/static/js/0.chunk.js:35023:38)
    at flushWork (http://localhost:3000/static/js/0.chunk.js:34979:20)

**Comment by dopecodez** [comment]
Which browser did you try it on? Also, could you share me the code snippet you are using?

**Comment by dopecodez** [comment]
On investigation, looks like this is a [known issue](https://github.com/electron/electron/issues/4270) with electron. It also says it could be a problem with [browserify](https://github.com/browserify/browserify) and i currently can't find any solutions for this. Would you be using browserify in your code?

I am expecting `os.platform` to return a valid value, but looks like this is overridden in this case.

**Comment by gautamkrishnar** [comment]
@igsnow you don't have to use browser fly for this library to work since electron supports most node APIs.

**Comment by dopecodez** [comment]
Any updates, @igsnow ?

**Comment by dopecodez** [comment]
Closing as issue is stale, and looks unrelated to `pingman`. For people searching for a solution, you can use the one listed here, or open an issue in the electron repository.
